"""add development plan geographies

Revision ID: 2535579a588e
Revises: a9f3e5e747b5
Create Date: 2023-10-10 16:41:26.293304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2535579a588e"
down_revision = "a9f3e5e747b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "development_plan_geography",
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("prefix", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("geometry", sa.Text(), nullable=True),
        sa.Column("point", sa.Text(), nullable=True),
        sa.Column("development_plan_geography_type", sa.Text(), nullable=True),
        sa.Column("development_plan_reference", sa.Text(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["development_plan_reference"],
            ["development_plan.reference"],
        ),
        sa.PrimaryKeyConstraint("reference"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("development_plan_geography")
    # ### end Alembic commands ###
