"""add development plan geography geojson

Revision ID: 2cdebf46a015
Revises: 2535579a588e
Create Date: 2023-10-11 10:37:53.994324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cdebf46a015"
down_revision = "2535579a588e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("development_plan_geography", schema=None) as batch_op:
        batch_op.add_column(sa.Column("geojson", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("development_plan_geography", schema=None) as batch_op:
        batch_op.drop_column("geojson")

    # ### end Alembic commands ###
