"""Add adopted-date field to plan

Revision ID: 4d9c0c4a7e08
Revises: 688e399bd69e
Create Date: 2023-10-03 14:58:44.816589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d9c0c4a7e08"
down_revision = "688e399bd69e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("development_plan", schema=None) as batch_op:
        batch_op.add_column(sa.Column("adopted_date", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("development_plan", schema=None) as batch_op:
        batch_op.drop_column("adopted_date")

    # ### end Alembic commands ###
