"""remove unused boundary fields

Revision ID: 9b6eb4a2f40d
Revises: ff70868669f3
Create Date: 2024-09-13 10:51:44.607056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b6eb4a2f40d"
down_revision = "ff70868669f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("development_plan_boundary", schema=None) as batch_op:
        batch_op.drop_column("prefix")
        batch_op.drop_column("notes")
        batch_op.drop_column("point")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("development_plan_boundary", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("point", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("prefix", sa.TEXT(), autoincrement=False, nullable=True)
        )
    # ### end Alembic commands ###
