"""table renamings

Revision ID: 9da023153749
Revises: 624ea9cb3155
Create Date: 2024-09-06 14:53:04.213477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9da023153749"
down_revision = "624ea9cb3155"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("development_plan_event", "development_plan_timetable")
    op.rename_table("development_plan_event_type", "development_plan_event")

    op.drop_column("development_plan_timetable", "development_plan_event")
    op.alter_column(
        "development_plan_timetable",
        "development_plan_event_type_reference",
        new_column_name="development_plan_event",
    )
    op.alter_column(
        "development_plan_timetable",
        "development_plan_reference",
        new_column_name="development_plan",
    )

    op.rename_table(
        "development_plan_event_organisation", "development_plan_timetable_organisation"
    )
    op.alter_column(
        "development_plan_timetable_organisation",
        "development_plan_event",
        new_column_name="development_plan_timetable",
    )

    op.rename_table("development_plan_geography", "development_plan_boundary")
    op.rename_table("development_plan_geography_type", "development_plan_boundary_type")

    op.alter_column(
        "development_plan_boundary",
        "development_plan_geography_type_reference",
        new_column_name="development_plan_boundary_type",
    )
    op.alter_column(
        "development_plan_boundary",
        "development_plan_reference",
        new_column_name="development_plan",
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("development_plan_event", "development_plan_event_type")
    op.rename_table("development_plan_timetable", "development_plan_event")

    op.alter_column(
        "development_plan_event",
        "development_plan_event",
        new_column_name="development_plan_event_type_reference",
    )
    op.add_column(
        "development_plan_event",
        sa.Column("development_plan_event", sa.TEXT(), nullable=True),
    )
    op.alter_column(
        "development_plan_event",
        "development_plan",
        new_column_name="development_plan_reference",
    )

    op.rename_table(
        "development_plan_timetable_organisation", "development_plan_event_organisation"
    )
    op.alter_column(
        "development_plan_event_organisation",
        "development_plan_timetable",
        new_column_name="development_plan_event",
    )

    op.rename_table("development_plan_boundary_type", "development_plan_geography_type")
    op.rename_table("development_plan_boundary", "development_plan_geography")

    op.alter_column(
        "development_plan_geography",
        "development_plan_boundary_type",
        new_column_name="development_plan_geography_type_reference",
    )
    op.alter_column(
        "development_plan_geography",
        "development_plan",
        new_column_name="development_plan_reference",
    )

    # ### end Alembic commands ###
