"""change org relations to many to many

Revision ID: b50b1d73dff9
Revises: aa48f8eccdb8
Create Date: 2023-04-14 16:14:11.806609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b50b1d73dff9"
down_revision = "aa48f8eccdb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "development_plan_organisation",
        sa.Column("development_plan", sa.Text(), nullable=True),
        sa.Column("organisation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["development_plan"],
            ["development_plan.reference"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation"],
            ["organisation.organisation"],
        ),
    )
    op.create_table(
        "development_plan_document_organisation",
        sa.Column("development_plan_document", sa.Text(), nullable=True),
        sa.Column("organisation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["development_plan_document"],
            ["development_plan_document.reference"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation"],
            ["organisation.organisation"],
        ),
    )
    op.create_table(
        "development_plan_timetable_organisation",
        sa.Column("development_plan_timetable", sa.Text(), nullable=True),
        sa.Column("organisation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["development_plan_timetable"],
            ["development_plan_timetable.reference"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation"],
            ["organisation.organisation"],
        ),
    )
    with op.batch_alter_table("development_plan", schema=None) as batch_op:
        batch_op.drop_constraint(
            "development_plan_organisation_id_fkey", type_="foreignkey"
        )
        batch_op.drop_column("organisation_id")

    with op.batch_alter_table("development_plan_document", schema=None) as batch_op:
        batch_op.drop_constraint(
            "development_plan_document_organisation_id_fkey", type_="foreignkey"
        )
        batch_op.drop_column("organisation_id")

    with op.batch_alter_table("development_plan_timetable", schema=None) as batch_op:
        batch_op.drop_constraint(
            "development_plan_timetable_organisation_id_fkey", type_="foreignkey"
        )
        batch_op.drop_column("organisation_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("development_plan_timetable", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("organisation_id", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "development_plan_timetable_organisation_id_fkey",
            "organisation",
            ["organisation_id"],
            ["organisation"],
        )

    with op.batch_alter_table("development_plan_document", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("organisation_id", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "development_plan_document_organisation_id_fkey",
            "organisation",
            ["organisation_id"],
            ["organisation"],
        )

    with op.batch_alter_table("development_plan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("organisation_id", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "development_plan_organisation_id_fkey",
            "organisation",
            ["organisation_id"],
            ["organisation"],
        )

    op.drop_table("development_plan_timetable_organisation")
    op.drop_table("development_plan_document_organisation")
    op.drop_table("development_plan_organisation")
    # ### end Alembic commands ###
