"""add development plan boundary key to plan

Revision ID: d3db89280ef7
Revises: 9da023153749
Create Date: 2024-09-10 12:58:22.477884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3db89280ef7"
down_revision = "9da023153749"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("development_plan", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("development_plan_boundary", sa.Text(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_dev_plan_boundary_plan",
            "development_plan_boundary",
            ["development_plan_boundary"],
            ["reference"],
        )

    op.execute(
        """
        UPDATE development_plan
        SET development_plan_boundary = development_plan_boundary.reference
        FROM development_plan_boundary
        WHERE development_plan.reference = development_plan_boundary.development_plan
    """
    )

    with op.batch_alter_table("development_plan_boundary", schema=None) as batch_op:
        batch_op.drop_column("development_plan")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("development_plan_boundary", schema=None) as batch_op:
        batch_op.add_column(sa.Column("development_plan", sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(
            "fk_boundary_dev_plan",
            "development_plan",
            ["development_plan"],
            ["reference"],
        )

    op.execute(
        """
        UPDATE development_plan_boundary
        SET development_plan = development_plan.reference
        FROM development_plan
        WHERE development_plan_boundary.reference = development_plan.development_plan_boundary
    """
    )

    with op.batch_alter_table("development_plan", schema=None) as batch_op:
        batch_op.drop_constraint("fk_dev_plan_boundary_plan", type_="foreignkey")
        batch_op.drop_column("development_plan_boundary")

    # ### end Alembic commands ###
