"""add geometry, geojson and point data to org

Revision ID: e601e0d13cbf
Revises: 70cdd0c50132
Create Date: 2023-10-11 16:37:22.340537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e601e0d13cbf"
down_revision = "70cdd0c50132"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("geometry", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("geojson", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("point", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation", schema=None) as batch_op:
        batch_op.drop_column("point")
        batch_op.drop_column("geojson")
        batch_op.drop_column("geometry")

    # ### end Alembic commands ###
